networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      unlock:
        - 0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0
compiler:
  solc:
    version: 0.6.11
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
